services:
  db:
    image: postgres:16
    container_name: chat_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-chat}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: chat_adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  pg_data:

# Network configuration for sandbox containers
# The sandbox containers will be dynamically created by SessionManager
# and will connect to this network to communicate with the backend
networks:
  default:
    name: langgraph-network
    driver: bridge

